### PR TITLE
Issues and NuGet updates

### LINKED ISSUE #845: IBaseTestObject is named incorrectly based off of the interface name
https://github.com/Magenic/MAQS/blob/master/Framework/BaseTest/IBaseTestObject.cs

Filename is named incorrectly based off of the interface name

### LINKED ISSUE #846: ManagerStore is missing TryGetValue
In MAQS 7.0.1 the TryGetValue is missing from the Manager Store.  

Also potentially look into genericizing with a type

### LINKED ISSUE #849: Add .Net Analyzers to base projects
``` xml
<PropertyGroup>
  <LangVersion>latest</LangVersion>
  <EnableNETAnalyzers>true</EnableNetAnalyzers>
  <AnalysisLevel>latest</AnalysisLevel>
</PropertyGroup>
```

### PR DESCRIPTION
**Pull request by FermJacob**
Closes #849 
Closes #846 
Closes #845

### CODE REVIEW

File: Framework/BaseTest/IManagerStore.cs [hunk 1]
```diff
@@ -113,5 +113,16 @@ public interface IManagerStore : IDisposable
...
+        /// <summary>
+        ///  Gets the value associated with the specified key
+        /// </summary>
+        /// <typeparam name="T">Driver type</typeparam>
+        /// <param name="key">Key name</param>
+        /// <param name="driver">Driver to return</param>
+        /// <returns>True if it finds the driver based on key</returns>
+        bool TryGetDriver<T>(string key, out T driver);
+
+        bool TryGetManager<T>(string key, out T driver) where T : IDriverManager;
```
Comment (TroyWalshProf) [inline Framework/BaseTest/IManagerStore.cs:133]: Missing xml comments

**Review by TroyWalshProf — APPROVED** [review]
