### PR TITLE
Closes #331

### LINKED ISSUE #331: Fix failing Axe logger unit test
Message: 
    Assert.IsTrue failed. Expected to find 52 inapplicable matches.
  Stack Trace: 
    SeleniumUtilsTest.AccessibilityCheckVerbose()

### PR DESCRIPTION
**Pull request by FermJacob**
Closes #331

### CODE REVIEW

File: Framework/SeleniumUnitTests/SeleniumUtilsTest.cs [hunk 1]
```diff
@@ -335,8 +335,8 @@ public void AccessibilityCheckVerbose()
 
             string logContent = File.ReadAllText(filePath);
 
-            Assert.IsTrue(logContent.Contains("Found 18 items"), "Expected to find 18 pass matches.");
```
Comment (JeffreyZacher) [inline Framework/SeleniumUnitTests/SeleniumUtilsTest.cs:338]: update assert message
