### PR TITLE
SoftAssert Expected Asserts

### LINKED ISSUE #51: Pre-defined soft-asserts
We should allow tests to "pre-register" the SoftAsserts they intend to check. 
If, upon completion, they have not issued a SoftAssert for one of the pre-registered asserts, the test result should be changed to "Inconclusive". 

Background: if a test exits pre-maturely (coding logic error), without there being a failed assertion (soft, or otherwise), the test would blindly PASS, hiding an issue.

### PR DESCRIPTION
**Pull request by skalpin**
- Let's a user specify asserts that are expected to be called by the
  test method.
- Specify expected asserts using an attribute or manually by calling
  ExpectedAsserts(...)

Closes #51

### CODE REVIEW

File: Framework/BaseTest/BaseTest.cs [hunk 1]
```diff
@@ -550,6 +580,36 @@ private string GetFullyQualifiedTestClassNameNunit()
...
+        /// <param name="className">The fully qualified class name of the method.</param>
+        /// <param name="testName">The name of the test method.</param>
+        /// <returns>The method information from the test.</returns>
+        private MethodInfo GetMethodInfoFromClassAndTestName(string className, string testName)
+        {
+            foreach(var assemblyName in AppDomain.CurrentDomain.GetAssemblies())
+            {
+                try
+                {
+                    var loadedAssembly = Assembly.Load(assemblyName.ToString());
```
Comment (skalpin) [inline Framework/BaseTest/BaseTest.cs:596]: I'm concerned that looping through the assemblies in the application domain and loading them to get the current test class could be expensive. I would like to work with the team and benchmark this to see if it's really a problem.

**Comment by skalpin** [comment]
Closes #51

File: Framework/BaseTest/SoftAssert.cs [hunk 2]
```diff
@@ -22,6 +24,16 @@ public class SoftAssert
         /// </summary>
         private readonly List<string> listOfExceptions = new List<string>();
```
Comment (FermJacob) [inline Framework/BaseTest/SoftAssert.cs:25]: Was this going to be removed?  Or is it because it is still implemented in IsTrue and IsFalse?

File: Framework/BaseTest/SoftAssert.cs [hunk 3]
```diff
@@ -253,13 +266,32 @@ public void FailTestIfAssertFailed(string message)
...
         /// <summary>
         /// Wrap an assert inside a soft assert
         /// </summary>
         /// <param name="assertFunction">The assert function</param>
+        /// <param name="assertCalledKey">Key of expected assert being called.</param>
         /// <returns>True if the asset passed</returns>
-        public bool Assert(Action assertFunction)
+        public bool Assert(Action assertFunction, string assertCalledKey = null)
         {
+            if(_expectedAsserts.Any() && !string.IsNullOrEmpty(assertCalledKey))
```
[the remark this answers is not in the document]
Comment (skalpin) [reply Framework/BaseTest/SoftAssert.cs:290]: ya I'll change that

File: Framework/BaseTest/SoftAssert.cs (hunk 2 above)
Comment (skalpin) [reply Framework/BaseTest/SoftAssert.cs:25]: I do want to change this, but in a different PR.

File: Framework/BaseTest/BaseTest.cs (hunk 1 above)
Comment (skalpin) [reply Framework/BaseTest/BaseTest.cs:596]: I added a lengthy comment to the BaseTest `TestMethodInfo` property that explains the AppDomain is searched for the first assembly that can load the fully qualified class name.
Also the TestMethodInfo is lazy loaded, to mitigate performance issues.

I think performance impact will be minimal.

File: Framework/BaseTest/SoftAssert.cs (hunk 2 above)
Comment (FermJacob) [reply Framework/BaseTest/SoftAssert.cs:25]: #562

**Review by FermJacob — APPROVED** [review]
