### PR TITLE
Impement SoftAssert.Assert overrides for SeleniumSoftAssert and AppiumSoftAssert

### LINKED ISSUE #531: SeleniumSoftAssert and AppiumSoftAssert do not have overrides for the Assert(Func)
SeleniumSoftAssert and AppiumSoftAssert are missing overrides for the Assert(Func) method.  This means we are not receiving screenshots when an assertion fails and only logs.

### PR DESCRIPTION
**Pull request by FermJacob**
Closes #531

### CODE REVIEW

File: Framework/BaseAppiumTest/AppiumSoftAssert.cs [hunk 1]
```diff
@@ -65,6 +65,34 @@ public override bool AreEqual(string expectedText, string actualText, string sof
...
         }
 
+        /// <summary>
+        /// Soft assert method to check if the Action is false
+        /// </summary>
+        /// <param name="assertFunction">Function to use</param>
+        /// <param name="failureMessage">Message to log</param>
+        /// <param name="assertCalledKey">Key of expected assert being called.</param>
+        /// <returns>Boolean of the assert</returns>
+        public override bool Assert(Action assertFunction, string failureMessage = "", string assertCalledKey = null)
```
Comment (FermJacob) [inline Framework/BaseAppiumTest/AppiumSoftAssert.cs:75]: @TroyWalshProf Do we want a soft assert name parameter?

**Review by TroyWalshProf — APPROVED** [review]
